# copy code to the VM
- name: Install the aws ca bundle
  get_url:
    url: "https://s3.amazonaws.com/rds-downloads/rds-combined-ca-bundle.pem"
    dest: "{{ app_install_root }}/{{ app_repo_name }}/rds-combined-ca-bundle.pem"
